addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"             % "0.11.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.github.sbt"   % "sbt-github-actions"        % "0.23.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.5.2")
//addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.0")
